str_labels_mimic = [
    'No Finding',
    'Enlarged Cardiomediastinum',
    'Cardiomegaly',
    'Lung Lesion',
    'Lung Opacity',
    'Edema',
    'Consolidation',
    'Pneumonia',
    'Atelectasis',
    'Pneumothorax',
    'Pleural Effusion',
    'Pleural Other',
    'Fracture',
    'Support Devices']

list_labels = ['Edema',
'Opacity',
'Pneumothorax',
'Pleural abnormality',
'Lung Lesion',
'Atelectasis',
'Consolidation',
'Fracture',
'Cardiomegaly',
'Abnormal Mediastinum Contour']

translate_mimic_to_label = {'Edema':['Edema','Opacity'], 
'Pneumothorax':['Pneumothorax'], 
'Pleural Other':['Pleural abnormality'],
'Pleural Effusion':['Pleural abnormality'],
'Lung Lesion':['Lung Lesion', 'Opacity'],
'Atelectasis':['Atelectasis', 'Opacity'],
'Consolidation':['Consolidation', 'Opacity'],
'Fracture':['Fracture'],
'Lung Opacity':['Opacity'],
'Pneumonia': ['Opacity'],
'Cardiomegaly':['Cardiomegaly'],
'Enlarged Cardiomediastinum':['Abnormal Mediastinum Contour']}

translate_et_to_label = {'Pulmonary edema':['Edema','Opacity'], 
'Pneumothorax':['Pneumothorax'], 
'Pleural abnormality':['Pleural abnormality'],
'Pleural thickening':['Pleural abnormality'],
'Pleural effusion':['Pleural abnormality'],
'Lung nodule or mass':['Lung Lesion', 'Opacity'],
'Nodule':['Lung Lesion', 'Opacity'],
'Mass':['Lung Lesion', 'Opacity'],
'Atelectasis':['Atelectasis', 'Opacity'],
'Consolidation':['Consolidation', 'Opacity'],
'Acute fracture':['Fracture'],
'Fracture':['Fracture'],
'Groundglass opacity':['Opacity'],
'Interstitial lung disease': ['Opacity'],
'Fibrosis': ['Opacity'],
'Enlarged cardiac silhouette':['Cardiomegaly'],
'Abnormal mediastinal contour':['Abnormal Mediastinum Contour'],
'Wide mediastinum':['Abnormal Mediastinum Contour'],
'wide mediastinum & abnormal mediastinum contour':['Abnormal Mediastinum Contour'],
'interstitial lung disease & fibrosis':['Opacity'],
'acute fracture & fracture':['Fracture']}